### PR TITLE
Correctly highlight lines from tags matches

### PR DESCRIPTION
**Pull request by brandon-rhodes**
Before we were highlighting the entire symbol returned from a tags
search, but now we’ll just highlight the actual search term for the
frequent cases where the user has typed only a prefix of the symbol.

### CODE REVIEW

**Comment by brandon-rhodes** [comment]
Before:

image

After:

image

**Comment by brandon-rhodes** [comment]
This also simplifies how the tags search works. Instead of repeatedly mutating the original query and then having to restore its state at the end, it now passes its specialty RE through a second argument.

**Comment by nelhage** [comment]
👍  with a rebase on #192

**Comment by brandon-rhodes** [comment]
It's now atop 192 and it looks like tests are passing! :)

**Comment by nelhage** [comment]
btw, I believe I've given you merge permission, and please feel free to click the button yourself in a case like this! Thanks for all the contributions back.

**Comment by nelhage** [comment]
Ah, my bad, I hadn't! I've sent you an invite. I'll continue to review PRs, but I'm fine with merges if I've asked for trivial feedback, or if a coworker feels comfortable doing a review!

**Comment by brandon-rhodes** [comment]
Wow, thanks! :)

**Pull request merged**
